[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace = "4YwxioVsvLS8LMopNvmS4vr8znBZZ3gNAgBqQXmUvTrU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kubanemil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
