[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "FHpiZH2awuTi1QvbU6XR15AiCfetEk62oA9BWUn2LxaK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/emil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
